const INTERNAL_OPERATIONS = 'internal_operations';

const WAIV_OPERATIONS_TYPES = {
  TOKENS_TRANSFER: 'tokens_transfer',
  TRANSFER_TO_SAVINGS: 'transfer_to_savings',
  TRANSFER_FROM_SAVINGS: 'transfer_from_savings',
  PROPOSAL_PAY: 'proposal_pay',
  CUSTOM_JSON: 'custom_json',
  MARKET_BUY: 'market_buy',
  MARKET_SELL: 'market_sell',
  TOKENS_STAKE: 'tokens_stake',
  CURATION_REWARDS: 'comments_curationReward',
  AUTHOR_REWARDS: 'comments_authorReward',
  BENEFICIARY_REWARD: 'comments_beneficiaryReward',
};

// не все типы нужны
exports.ADVANCED_WALLET_TYPES = [
  INTERNAL_OPERATIONS,
  WAIV_OPERATIONS_TYPES.TOKENS_TRANSFER,
  WAIV_OPERATIONS_TYPES.TRANSFER_TO_SAVINGS,
  WAIV_OPERATIONS_TYPES.TRANSFER_FROM_SAVINGS,
  WAIV_OPERATIONS_TYPES.PROPOSAL_PAY,
  WAIV_OPERATIONS_TYPES.MARKET_BUY,
  WAIV_OPERATIONS_TYPES.MARKET_SELL,
  WAIV_OPERATIONS_TYPES.TOKENS_STAKE,
  WAIV_OPERATIONS_TYPES.AUTHOR_REWARDS,
  WAIV_OPERATIONS_TYPES.BENEFICIARY_REWARD,
  WAIV_OPERATIONS_TYPES.CURATION_REWARDS,
];

exports.SAVINGS_TRANSFERS = ['transfer_from_savings', 'transfer_to_savings'];
