version: '3.7'

services:
  main:
    container_name: waivio-api
    build: .
    command: npm run start
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    env_file:
      - .env
    network_mode: host

  secondary:
    container_name: waivio-api-secondary
    build: .
    command: npm run start
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    env_file:
      - .secondary.env
    network_mode: host
