version: '3.7'

services:
  main:
    container_name: waivio-api
    build: .
    command: npm run start
    restart: always
    network_mode: host
    mem_limit: 450m
    mem_reservation: 200M
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    env_file:
      - ./.env
