version: '3.7'

services:
  main:
    container_name: waivio-api
    build: .
    command: npm run start
    restart: always
    network_mode: host
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 450M
        reservations:
          memory: 200M
    env_file:
      - ./.env
