module.exports = {
  objectsFilter: require('./objectsFilter'),
  manage: require('./manage'),
  reports: require('./reports'),
  authorities: require('./authorities'),
  refunds: require('./refunds'),
  create: require('./create'),
  remove: require('./remove'),
  configurations: require('./configurations'),
  collectSiteDebts: require('./collectSiteDebts'),
  map: require('./map'),
  mapCoordinates: require('./mapCoordinates'),
  sitesNotifications: require('./sitesNotifications'),
  restrictions: require('./restrictions'),
  prefetchWobjs: require('./prefetchWobjs'),
  sitesStatistic: require('./sitesStatistic'),
};
