module.exports = {
  AppFactory: require('./AppFactory/AppFactory'),
  CommentFactory: require('./CommentFactory/CommentFactory'),
  PostFactory: require('./PostFactory/PostFactory'),
  ObjectFactory: require('./ObjectFactory/ObjectFactory'),
  SubscriptionsFactory: require('./Subscriptions/SubscriptionsFactory'),
  AppendObjectFactory: require('./ObjectFactory/AppendObjectFactory'),
  ObjectTypeFactory: require('./ObjectTypeFactory/ObjectsTypeFactory'),
  WebsitePaymentsFactory: require('./WebsitePaymentsFactory/WebsitePaymentsFactory'),
  UsersFactory: require('./UsersFactory/UsersFactory'),
  CampaignFactory: require('./CampaignFactory/CampaignFactory'),
  Campaign2Factory: require('./Campaign2Factory/Campaign2Factory'),
  CampaignPostFactory: require('./CampaignPosts/CampaignPostFactory'),
  UserWobjectsFactory: require('./UserWobjectsFactory/UserWobjectsFactory'),
  BotUpvoteFactory: require('./BotUpvote/BotUpvoteFactory'),
  PaymentHistoryFactory: require('./PaymentHistory/PaymentHistoryFactory'),
  RelatedFactory: require('./Related/RelatedFactory'),
  GeoIpFactory: require('./GeoIpFactory/GeoIpFactory'),
  HiddenPostsFactory: require('./HiddenPosts/HiddenPostsFactory'),
  MutedUsersFactory: require('./MutedUsers/MutedUsersFactory'),
  PrefetchFactory: require('./PrefetchFactory/PrefetchFactory'),
};
