module.exports = {
  getShopDepartments: require('./mainShop/getShopDepartments'),
  getShopFeed: require('./mainShop/getShopFeed'),
  getDepartmentFeed: require('./mainShop/getDepartmentFeed'),
  getShopFilters: require('./mainShop/getShopFilters'),
  getUserDepartments: require('./userShop/getUserDepartments'),
  getUserFeed: require('./userShop/getUserFeed'),
  getUserDepartmentFeed: require('./userShop/getUserDepartmentFeed'),
  getWobjectDepartments: require('./objectShop/getWobjectDepartments'),
  getWobjectDepartmentFeed: require('./objectShop/getWobjectDepartmentFeed'),
  getWobjectMainFeed: require('./objectShop/getWobjectMainFeed'),
  userFilters: require('./userShop/getUserFilters'),
  objectFilters: require('./objectShop/getWobjectFilters'),
  restoreShopState: require('./restoreShopState'),
  getReference: require('./getReference'),
};
